// Mocks generated by Mockito 5.4.6 from annotations
// in dragonball_heroes/test/features/characters/bloc/characters_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dragonball_heroes/features/characters/bloc/characters_repo.dart'
    as _i2;
import 'package:dragonball_heroes/features/models/models.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCharactersResponse_0 extends _i1.SmartFake
    implements _i2.CharactersResponse {
  _FakeCharactersResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCharacterModel_1 extends _i1.SmartFake
    implements _i3.CharacterModel {
  _FakeCharacterModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CharactersRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCharactersRepository extends _i1.Mock
    implements _i2.CharactersRepository {
  MockCharactersRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CharactersResponse> getCharacters({
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCharacters, [], {#page: page, #limit: limit}),
            returnValue: _i4.Future<_i2.CharactersResponse>.value(
              _FakeCharactersResponse_0(
                this,
                Invocation.method(#getCharacters, [], {
                  #page: page,
                  #limit: limit,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.CharactersResponse>);

  @override
  _i4.Future<_i3.CharacterModel> getCharacter(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCharacter, [id]),
            returnValue: _i4.Future<_i3.CharacterModel>.value(
              _FakeCharacterModel_1(
                this,
                Invocation.method(#getCharacter, [id]),
              ),
            ),
          )
          as _i4.Future<_i3.CharacterModel>);
}
